title: Géostandards Risques - Cartographies de la Directive Inondation
description: La famille des Géostandards Risques a pour objectif de standardiser les données numériques géographiques relatives aux procédures réglementaires de prévention des risques. Ce document est le profil applicatif dédié aux cartographies de la Directive Inondation.
homepage: https://github.com/cnigfr/Geostandards-risques-carto-di
version: 0.0.1
